### ISSUE TITLE
Bulk SMS Service provider

### ISSUE THREAD

**Issue by vinod-github** [vinod-github/cricquack#7]
Will need bulk sms service provider so as we can send users sms for registration code and invitation.

FYI - We need application to person a2p sms service providers.

**Comment by vinod-github** [comment]
https://www.nexmo.com/pricing/

This can help. It is used by Viber

**Comment by jaycriklover** [comment]
anything available which is known as free?

**Comment by vinod-github** [comment]
No Idea. You need to research on this part.

**Comment by jaycriklover** [comment]
ok kool..
